export const SET_DOUGH = 'SET_DOUGH';
export const DELETE_DOUGH = 'DELETE_DOUGH';
export const TOGGLE_INGREDIENT = 'TOGGLE_INGREDIENT';
export const DELETE_INGREDIENTS = 'DELETE_INGREDIENTS';
export const CREATE_PIZZA = 'CREATE_PIZZA';
export const DELETE_PIZZA = 'DELETE_PIZZA';
export const DELETE_PIZZAS = 'DELETE_PIZZAS';
